name: mmoChatPirate
main: mmo.Chat.MMOChatPirate
version: 1.0
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [mmoCore,mmoChat]

description: Adds "Pirate" to the chat filters
permissions:
  mmo.chat.pirate:
    description: Allows the use of the "Pirate" chat filter (otherwise it will be untranslated)
    default: true
