name: mmoChatPirate
version: ${releaseVersion}.${buildNumber}
description: Adds "Pirate" filter to mmoChat.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Chat.MMOChatPirate
depend: [Spout, mmoCore, mmoChat]

permissions:
    mmo.chat.pirate:
        description: Allows the use of the "Pirate" chat filter (otherwise it will be untranslated)
        default: true
